const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { Miniflare, convertV4MiniflareOptions } = require(process.env.MINIFLARE_MODULE || 'miniflare');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { randomUUID } = require('node:crypto');
(async () => {
  const base = process.argv[2] || 'http://127.0.0.1:8788';
  assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname));
  const config = JSON.parse(fs.readFileSync('wrangler.jsonc', 'utf8'));
  assert.equal(config.d1_databases[0].remote, false);
  const runtime = new Miniflare(convertV4MiniflareOptions({ modules: true, script: 'export default {}', resourcePersistencePath: path.resolve('.wrangler/state/v3'), d1Databases: { DB: config.d1_databases[0].database_id } }));
  const db = await runtime.getD1Database('DB');
  const read = async () => (await (await fetch(base + '/api/characters')).json());
  const initial = await read();
  const original = initial.characters.find(character => character.CLASS === 'Warlock' && character.SUBCLASS);
  const prefix = `Interfaz ${randomUUID().slice(0, 8)}`;
  const newClass = `${prefix} clase`, newSub = `${prefix} subclase`, newSpecies = `${prefix} especie`;
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1900, height: 1100 }, colorScheme: 'dark' });
  const errors = [], writes = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.method() === 'PATCH') writes.push(request.postDataJSON()); });
  const row = () => page.locator(`tr[data-character-id="${original.id}"]`);
  const select = field => row().locator(`select[data-editor="${field}"]`);
  const input = field => row().locator(`input[data-editor="${field}"]`);
  const patch = async fields => {
    const current = (await read()).characters.find(character => character.id === original.id);
    return fetch(base + '/api/characters/batch', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ changes: [{ id: current.id, expectedVersion: current.version, fields }] }) });
  };
  try {
    await page.goto(base); await page.waitForSelector('tbody tr');
    await page.fill('#name-search', original.PERSONAJE);
    await page.click('#edit-button');
    assert.equal(await select('SPECIE').locator('option').count(), 181);
    await select('CLASS').selectOption('Ranger');
    assert.equal(await select('SUBCLASS').inputValue(), '');
    const rangerOptions = await select('SUBCLASS').locator('option').allTextContents();
    assert.ok(rangerOptions.includes('Phantom'));
    assert.ok(!rangerOptions.includes('Oath of Devotion'));
    await select('SUBCLASS').selectOption('Phantom');
    await select('CLASS').selectOption('Rogue');
    assert.equal(await select('SUBCLASS').inputValue(), 'Phantom');
    await select('CLASS').selectOption('');
    assert.equal(await select('SUBCLASS').isDisabled(), true);
    assert.equal(await select('SUBCLASS').inputValue(), '');
    await select('CLASS').selectOption('__new');
    await input('CLASS').fill(newClass);
    assert.equal(await select('SUBCLASS').isDisabled(), false);
    await select('SUBCLASS').selectOption('__new');
    await input('SUBCLASS').fill(newSub);
    await select('SPECIE').selectOption('__new');
    await input('SPECIE').fill(newSpecies);
    await row().locator('textarea[data-editor="NOTAS"]').fill('Nota con catálogo');
    assert.equal(writes.length, 0);
    const before = await read();
    assert.ok(!before.catalogs.classes.some(option => option.name === newClass));
    await page.locator('.table-scroll').evaluate(element => { element.scrollLeft = 0; });
    await page.screenshot({ path: '.local/006-edicion.png' });
    await page.click('#edit-button');
    await page.waitForFunction(() => document.querySelector('#edit-button').textContent === 'Editar');
    assert.equal(writes.length, 1);
    assert.deepEqual(writes[0].catalogAdditions, { classes: [newClass], subclasses: [{ className: newClass, name: newSub }], species: [newSpecies] });
    await page.reload(); await page.waitForSelector('tbody tr');
    await page.click('#edit-button');
    assert.equal(await select('CLASS').inputValue(), newClass);
    assert.equal(await select('SUBCLASS').inputValue(), newSub);
    assert.equal(await select('SPECIE').inputValue(), newSpecies);
    await select('SPECIE').selectOption('__new'); await input('SPECIE').fill(`${prefix} revertida`);
    await select('SPECIE').selectOption(newSpecies);
    const beforeEmpty = writes.length; await page.click('#edit-button');
    assert.equal(writes.length, beforeEmpty);
    assert.ok(!(await read()).catalogs.species.some(option => option.name === `${prefix} revertida`));
    await page.click('#edit-button');
    await select('SUBCLASS').selectOption('__new'); await input('SUBCLASS').fill(`${prefix} anterior`);
    assert.equal((await patch({ CLASS: 'Ranger', SUBCLASS: 'Phantom' })).status, 200);
    await page.click('#edit-button'); await page.waitForSelector('#refresh-draft:visible');
    await page.click('#refresh-draft'); await page.waitForFunction(() => !document.querySelector('#edit-button').disabled);
    const beforeWrongParent = writes.length;
    await page.click('#edit-button');
    assert.equal(writes.length, beforeWrongParent);
    assert.match(await page.locator('#draft-status').textContent(), /La clase ha cambiado/);
    await select('SUBCLASS').selectOption('Hunter');
    await page.click('#edit-button'); await page.waitForFunction(() => document.querySelector('#edit-button').textContent === 'Editar');
    assert.ok(!(await read()).catalogs.subclasses.some(option => option.name === `${prefix} anterior`));
    await page.click('#edit-button');
    await select('SPECIE').selectOption('__new'); await input('SPECIE').fill(`${prefix} perdida`);
    await page.route('**/api/characters/batch', async route => { await route.fetch(); await route.abort('failed'); });
    await page.click('#edit-button'); await page.waitForSelector('#refresh-draft:visible');
    await page.unroute('**/api/characters/batch'); await page.click('#refresh-draft');
    await page.waitForFunction(() => !document.querySelector('#edit-button').disabled);
    assert.equal(await page.locator('tr.pending').count(), 0);
    const beforeRetry = writes.length; await page.click('#edit-button'); assert.equal(writes.length, beforeRetry);
    await page.click('#edit-button');
    await select('SPECIE').selectOption('__new'); await input('SPECIE').fill(`${prefix} conflicto`);
    assert.equal((await patch({ NOTAS: 'Cambio concurrente local' })).status, 200);
    await page.click('#edit-button'); await page.waitForSelector('#refresh-draft:visible');
    assert.ok(!(await read()).catalogs.species.some(option => option.name === `${prefix} conflicto`));
    await page.click('#refresh-draft'); await page.waitForFunction(() => !document.querySelector('#edit-button').disabled);
    assert.equal(await select('SPECIE').inputValue(), `${prefix} conflicto`);
    await page.click('#edit-button'); await page.waitForFunction(() => document.querySelector('#edit-button').textContent === 'Editar');
    await page.click('#theme-toggle'); await page.setViewportSize({ width: 390, height: 1400 }); await page.click('#edit-button');
    await page.locator('.table-scroll').evaluate(element => { element.scrollLeft = element.querySelector('th:nth-child(2)').offsetLeft - 20; });
    await page.screenshot({ path: '.local/006-movil.png' });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual(errors, []);
    console.log('006 navegador local: catálogos completos, dependencia/limpieza, opciones nuevas/revertidas, lote mixto, recarga, conflicto/respuesta perdida y móvil correctos.');
  } finally {
    assert.equal((await patch(Object.fromEntries(['CLASS', 'SUBCLASS', 'SPECIE', 'NOTAS'].map(field => [field, original[field]])))).status, 200);
    await db.batch([
      db.prepare('DELETE FROM subclasses WHERE name LIKE ?').bind(`${prefix}%`),
      db.prepare('DELETE FROM classes WHERE name LIKE ?').bind(`${prefix}%`),
      db.prepare('DELETE FROM species WHERE name LIKE ?').bind(`${prefix}%`)
    ]);
    await browser.close(); await runtime.dispose();
  }
})();
