const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const base = process.argv[2] || 'http://127.0.0.1:8788';
  assert.ok(['127.0.0.1', 'localhost'].includes(new URL(base).hostname));
  const read = async () => (await (await fetch(base + '/api/characters?pageSize=all')).json()).characters;
  const initial = await read();
  const original = initial.find(character => character.NIVEL < 20 && character.PERSONAJE && character.PROPIETARIO);
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1700, height: 1000 }, colorScheme: 'dark' });
  const errors = [];
  const writes = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.method() === 'PATCH') writes.push(request.postDataJSON()); });
  const row = () => page.locator(`tr[data-character-id="${original.id}"]`);
  const control = (field, tag = 'input') => row().locator(`${tag}[data-editor="${field}"]`);
  const patch = async fields => {
    const current = (await read()).find(character => character.id === original.id);
    return fetch(base + '/api/characters/batch', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ changes: [{ id: current.id, expectedVersion: current.version, fields }] }) });
  };
  try {
    await page.goto(base);
    await page.waitForSelector('tbody tr');
    await page.fill('#name-search', original.PERSONAJE);
    await page.selectOption('#filter-owner', original.PROPIETARIO);
    await page.click('#edit-button');
    await control('PERSONAJE').fill('x'.repeat(51));
    await page.click('#edit-button');
    assert.equal(writes.length, 0);
    await control('PERSONAJE').fill('Nombre de prueba local');
    await control('PERSONAJE').focus();
    await page.keyboard.press('Home');
    await page.keyboard.type('A');
    assert.equal(await control('PERSONAJE').inputValue(), 'ANombre de prueba local');
    assert.equal(await control('PERSONAJE').evaluate(element => element.selectionStart), 1);
    assert.equal(await row().count(), 1);
    await control('NOTAS', 'textarea').fill('Nota de prueba\n<b>Texto literal</b>');
    await control('ESTADO', 'select').selectOption('__new');
    await control('ESTADO').fill('Estado de prueba local');
    await control('PROPIETARIO', 'select').selectOption('__new');
    await control('PROPIETARIO').fill('Propietario de prueba local');
    assert.equal(writes.length, 0);
    await row().locator('button[data-delta="1"]').click();
    assert.equal(await control('PERSONAJE').inputValue(), 'ANombre de prueba local');
    assert.equal(await row().count(), 1);
    await page.screenshot({ path: '.local/005-edicion.png' });
    await page.click('#edit-button');
    await page.waitForFunction(() => document.querySelector('#edit-button').textContent === 'Editar');
    assert.equal(writes.length, 1);
    assert.deepEqual(Object.keys(writes[0].changes[0].fields).sort(), ['ESTADO', 'NIVEL', 'NOTAS', 'PERSONAJE', 'PROPIETARIO']);
    assert.equal(await row().count(), 0);
    await page.click('#reset-filters');
    await page.selectOption('#page-size', 'all');
    await page.waitForFunction(() => document.querySelectorAll('tbody tr').length === 203);
    assert.equal(await page.locator('tbody tr').count(), 203);
    assert.equal(await page.locator('tbody b').count(), 0);
    await page.reload();
    await page.waitForSelector('tbody tr');
    await page.click('#edit-button');
    assert.equal(await control('PERSONAJE').inputValue(), 'ANombre de prueba local');
    assert.equal(await control('NOTAS', 'textarea').inputValue(), 'Nota de prueba\n<b>Texto literal</b>');
    await control('NOTAS', 'textarea').fill('Mi nueva nota');
    assert.equal((await patch({ NOTAS: 'Nota concurrente' })).status, 200);
    await page.click('#edit-button');
    await page.waitForSelector('#refresh-draft:visible');
    await page.click('#refresh-draft');
    await page.waitForFunction(() => !document.querySelector('#edit-button').disabled);
    assert.match(await page.locator('#draft-status').textContent(), /Nota concurrente/);
    assert.equal(await control('NOTAS', 'textarea').inputValue(), 'Mi nueva nota');
    await page.click('#edit-button');
    await page.waitForFunction(() => document.querySelector('#edit-button').textContent === 'Editar');
    await page.click('#edit-button');
    await control('NOTAS', 'textarea').fill('Respuesta perdida');
    await page.route('**/api/characters/batch', async route => { await route.fetch(); await route.abort('failed'); });
    await page.click('#edit-button');
    await page.waitForSelector('#refresh-draft:visible');
    await page.unroute('**/api/characters/batch');
    await page.click('#refresh-draft');
    await page.waitForFunction(() => !document.querySelector('#edit-button').disabled);
    assert.equal(await page.locator('tr.pending').count(), 0);
    const before = writes.length;
    await page.click('#edit-button');
    assert.equal(writes.length, before);
    await page.click('#theme-toggle');
    await page.setViewportSize({ width: 390, height: 1400 });
    await page.click('#edit-button');
    await page.locator('.table-scroll').evaluate(element => { element.scrollLeft = element.querySelector('th:nth-child(7)').offsetLeft - 20; });
    await page.screenshot({ path: '.local/005-movil.png' });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    assert.deepEqual(errors, []);
    console.log('005 navegador local: cursor, límites, filtros retenidos, opciones nuevas, lote mixto, persistencia, conflicto, respuesta perdida, tema y móvil correctos.');
  } finally {
    assert.equal((await patch(Object.fromEntries(['PERSONAJE', 'NOTAS', 'ESTADO', 'PROPIETARIO', 'NIVEL'].map(field => [field, original[field]])))).status, 200);
    await browser.close();
  }
})();
