import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
import { validateCreation } from '../server/create-character.js';
const require = createRequire(import.meta.url);
const { Miniflare, convertV4MiniflareOptions } = require(process.env.MINIFLARE_MODULE || 'miniflare');
const base = process.argv[2] ?? 'http://127.0.0.1:8788';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname));
const config = JSON.parse(await fs.readFile('wrangler.jsonc', 'utf8'));
assert.equal(config.d1_databases[0].remote, false);
const runtime = new Miniflare(convertV4MiniflareOptions({ modules: true, script: 'export default {}', resourcePersistencePath: path.resolve('.wrangler/state/v3'), d1Databases: { DB: config.d1_databases[0].database_id } }));
const db = await runtime.getD1Database('DB');
const read = async () => (await (await fetch(`${base}/api/characters?pageSize=all`)).json());
const initial = await read();
const prefix = `Alta ${randomUUID().slice(0, 8)}`;
const ids = [];
const post = async body => fetch(`${base}/api/characters`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
const operation = () => { const id = randomUUID(); ids.push(id); return { id, fields: { PERSONAJE: prefix, CLASS: initial.catalogs.classes[0].name, SPECIE: initial.catalogs.species[0].name, PROPIETARIO: 'Prueba alta' } }; };
try {
  const body = operation();
  assert.equal(validateCreation(body).fields.NIVEL, 1);
  for (const field of ['PERSONAJE', 'CLASS', 'SPECIE', 'PROPIETARIO']) assert.equal((await post({ ...body, fields: { ...body.fields, [field]: '' } })).status, 422);
  for (const value of [null, 0, 21, 1.5, '1']) assert.equal((await post({ ...body, fields: { ...body.fields, NIVEL: value } })).status, 422);
  assert.equal((await post({ ...body, fields: { ...body.fields, version: 0 } })).status, 400);
  assert.equal((await post({ ...body, fields: { ...body.fields, PERSONAJE: '😀'.repeat(51) } })).status, 422);
  assert.equal((await fetch(`${base}/api/characters`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: 'https://other.test' }, body: JSON.stringify(body) })).status, 403);
  const first = await post(body);
  assert.equal(first.status, 201, await first.clone().text());
  const character = (await first.json()).character;
  assert.equal(character.NIVEL, 1); assert.equal(character.RANGO, 'Corvato'); assert.equal(character.version, 0); assert.equal(character.SUBCLASS, null);
  assert.equal((await post(body)).status, 200);
  assert.equal((await post({ ...body, fields: { ...body.fields, PERSONAJE: 'Otro' } })).status, 409);
  assert.equal((await read()).pagination.totalRecords, initial.characters.length + 1);
  const edited = await fetch(`${base}/api/characters/batch`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ changes: [{ id: body.id, expectedVersion: 0, fields: { NOTAS: 'Editado después' } }] }) });
  assert.equal(edited.status, 200);
  assert.equal((await (await post(body)).json()).character.NOTAS, 'Editado después');
  const simultaneous = operation();
  assert.deepEqual((await Promise.all([post(simultaneous), post(simultaneous)])).map(item => item.status).sort(), [200, 201]);
  const conflict = operation();
  assert.deepEqual((await Promise.all([post(conflict), post({ ...conflict, fields: { ...conflict.fields, PERSONAJE: 'Diferente' } })])).map(item => item.status).sort(), [201, 409]);
  const withCatalogs = operation();
  withCatalogs.fields.CLASS = `${prefix} clase`; withCatalogs.fields.SUBCLASS = `${prefix} sub`; withCatalogs.fields.SPECIE = `${prefix} especie`;
  withCatalogs.catalogAdditions = { classes: [withCatalogs.fields.CLASS], subclasses: [{ className: withCatalogs.fields.CLASS, name: withCatalogs.fields.SUBCLASS }], species: [withCatalogs.fields.SPECIE] };
  assert.equal((await post(withCatalogs)).status, 201);
  assert.equal((await post(withCatalogs)).status, 200);
  const shared = [operation(), operation()];
  for (const item of shared) { item.fields.CLASS = `${prefix} común`; item.fields.SUBCLASS = `${prefix} hija`; item.catalogAdditions = { classes: [item.fields.CLASS], subclasses: [{ className: item.fields.CLASS, name: item.fields.SUBCLASS }] }; }
  assert.deepEqual((await Promise.all(shared.map(post))).map(item => item.status), [201, 201]);
  const afterShared = await read();
  const common = afterShared.catalogs.classes.filter(item => item.name === `${prefix} común`);
  assert.equal(common.length, 1);
  assert.equal(afterShared.catalogs.subclasses.filter(item => item.classId === common[0].id).length, 1);
  assert.equal(new Set(afterShared.characters.map(item => item.sourceRow)).size, afterShared.characters.length);
  const rollback = operation(); rollback.fields.SPECIE = `${prefix} rollback`; rollback.catalogAdditions = { species: [rollback.fields.SPECIE] };
  await db.prepare(`CREATE TRIGGER test_creation_rollback BEFORE INSERT ON creation_requests WHEN NEW.character_id = '${rollback.id}' BEGIN SELECT RAISE(ABORT, 'forced'); END`).run();
  assert.equal((await post(rollback)).status, 503);
  assert.ok(!(await read()).catalogs.species.some(item => item.name === rollback.fields.SPECIE));
  assert.ok(!(await read()).characters.some(item => item.id === rollback.id));
  console.log('Creation API: validation, catalogues, >203, replay, edited replay, concurrency, rollback pass.');
} finally {
  await db.prepare('DROP TRIGGER IF EXISTS test_creation_rollback').run();
  for (const id of ids) { await db.prepare('DELETE FROM creation_requests WHERE character_id = ?').bind(id).run(); await db.prepare('DELETE FROM characters WHERE id = ?').bind(id).run(); }
  await db.prepare('DELETE FROM subclasses WHERE name LIKE ?').bind(`${prefix}%`).run();
  await db.prepare('DELETE FROM classes WHERE name LIKE ?').bind(`${prefix}%`).run();
  await db.prepare('DELETE FROM species WHERE name LIKE ?').bind(`${prefix}%`).run();
  assert.deepEqual(await read(), initial);
  await runtime.dispose();
}
