const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { Miniflare, convertV4MiniflareOptions } = require(process.env.MINIFLARE_MODULE || 'miniflare');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async () => {
  const base = 'http://127.0.0.1:8788';
  const config = JSON.parse(fs.readFileSync('wrangler.jsonc', 'utf8'));
  assert.equal(config.d1_databases[0].remote, false);
  const runtime = new Miniflare(convertV4MiniflareOptions({ modules: true, script: 'export default {}', resourcePersistencePath: path.resolve('.wrangler/state/v3'), d1Databases: { DB: config.d1_databases[0].database_id } }));
  const db = await runtime.getD1Database('DB');
  const initial = await (await fetch(base + '/api/characters?pageSize=all')).json();
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], created = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.method() === 'POST') created.push(request.postDataJSON().id); });
  try {
    await page.goto(base); await page.waitForSelector('tbody tr');
    await page.click('#create-button');
    assert.equal(await page.locator('#create-PERSONAJE').evaluate(element => element === document.activeElement), true);
    await page.keyboard.press('Escape'); assert.equal(await page.locator('#create-dialog').evaluate(element => element.open), false);
    assert.equal(created.length, 0);
    await page.click('#edit-button');
    const row = page.locator('tbody tr').first();
    await row.locator('input[data-editor="PERSONAJE"]').fill('Borrador conservado');
    await page.click('#next-page');
    await page.waitForFunction(() => !document.querySelector('#create-button').disabled);
    await page.locator('tbody tr').first().locator('input[data-editor="PERSONAJE"]').fill('Segundo borrador conservado');
    await page.click('#create-button');
    await page.fill('#create-PERSONAJE', 'Personaje prueba UI');
    await page.selectOption('#create-CLASS', initial.catalogs.classes[0].name);
    await page.selectOption('#create-SPECIE', initial.catalogs.species[0].name);
    await page.selectOption('#create-PROPIETARIO', '__new');
    await page.locator('[data-creation-field="PROPIETARIO"] input').fill('Prueba propietario');
    await page.locator('[data-creation-field="NIVEL"] button').first().click();
    assert.equal(await page.locator('[data-creation-field="NIVEL"] output').textContent(), '2');
    await page.screenshot({ path: '/private/tmp/nido-009-desktop.png' });
    await page.click('#submit-create');
    await page.waitForFunction(() => !document.querySelector('#create-dialog').open && !document.querySelector('#create-button').disabled);
    assert.equal(created.length, 1);
    assert.equal(await page.locator('input[data-editor="PERSONAJE"]').first().inputValue(), 'Segundo borrador conservado');
    assert.match(await page.locator('#draft-status').textContent(), /2 personajes/);
    assert.match(await page.locator('#creation-status').textContent(), /Personaje guardado/);
    const other = await browser.newPage(); await other.goto(base);
    await other.fill('#name-search', 'Personaje prueba UI'); await other.waitForFunction(() => document.querySelector('#result-status').textContent.includes('1 coincidencias'));
    assert.match(await other.locator('tbody').textContent(), /Personaje prueba UI/);
    await page.reload(); await page.waitForSelector('tbody tr');
    await page.click('#create-button');
    await page.fill('#create-PERSONAJE', 'Respuesta perdida UI');
    await page.selectOption('#create-CLASS', initial.catalogs.classes[0].name);
    await page.selectOption('#create-SPECIE', initial.catalogs.species[0].name);
    await page.selectOption('#create-PROPIETARIO', initial.editOptions.PROPIETARIO[0]);
    await page.route('**/api/characters', async route => { await route.fetch(); await route.abort('failed'); });
    await page.click('#submit-create');
    await page.waitForFunction(() => document.querySelector('#submit-create').textContent === 'Comprobar y reintentar');
    assert.equal(await page.locator('#cancel-create').isDisabled(), true);
    await page.keyboard.press('Escape'); assert.equal(await page.locator('#create-dialog').evaluate(element => element.open), true);
    await page.unroute('**/api/characters');
    const sends = created.length;
    await page.click('#submit-create');
    await page.waitForFunction(() => !document.querySelector('#create-dialog').open && !document.querySelector('#create-button').disabled);
    assert.equal(created.length, sends);
    await page.fill('#name-search', 'No coincide esta alta');
    await page.waitForFunction(() => document.querySelector('#result-status').textContent.includes('0 coincidencias'));
    await page.click('#create-button');
    await page.fill('#create-PERSONAJE', 'Alta fuera de filtro');
    await page.selectOption('#create-CLASS', initial.catalogs.classes[0].name);
    await page.selectOption('#create-SPECIE', initial.catalogs.species[0].name);
    await page.selectOption('#create-PROPIETARIO', initial.editOptions.PROPIETARIO[0]);
    await page.route('**/api/characters?*', route => route.fulfill({ status: 503, body: '{}' }));
    await page.click('#submit-create');
    await page.waitForFunction(() => document.querySelector('#creation-status').textContent.includes('No se pudo actualizar'));
    await page.unroute('**/api/characters?*');
    const beforeRefresh = created.length;
    await page.click('#retry-load');
    await page.waitForFunction(() => !document.querySelector('#create-button').disabled);
    assert.equal(created.length, beforeRefresh);
    assert.equal(await page.locator('#name-search').inputValue(), 'No coincide esta alta');
    assert.equal(await page.locator('tbody tr').count(), 0);
    await page.setViewportSize({ width: 320, height: 844 });
    await page.click('#theme-toggle');
    await page.click('#create-button');
    await page.screenshot({ path: '/private/tmp/nido-009-mobile.png' });
    assert.ok(await page.locator('#create-dialog').evaluate(element => element.getBoundingClientRect().width <= innerWidth));
    await page.click('#cancel-create');
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('Creation UI: focus, Escape/cancel, same controls, level, creation, draft retention, second session, 320px pass.');
  } finally {
    for (const id of created) { await db.prepare('DELETE FROM creation_requests WHERE character_id = ?').bind(id).run(); await db.prepare('DELETE FROM characters WHERE id = ?').bind(id).run(); }
    await browser.close(); await runtime.dispose();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
