const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
(async () => {
  const base = process.argv[2] || 'http://127.0.0.1:8788';
  assert.ok(['127.0.0.1', 'localhost'].includes(new URL(base).hostname), 'Solo pruebas locales.');
  const context = {};
  vm.createContext(context);
  vm.runInContext(fs.readFileSync('vendor/xlsx.full.min.js', 'utf8'), context);
  const xlsx = context.XLSX;
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  try {
    const page = await browser.newPage({ acceptDownloads: true });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    const settled = () => page.waitForFunction(() => document.querySelector('.results').getAttribute('aria-busy') === 'false' && document.querySelector('#error-state').hidden);
    await page.goto(base);
    await settled();
    const button = page.locator('#export-button');
    assert.equal(await page.locator('#characters-body tr').count(), 50);
    await page.click('#next-page');
    await settled();
    const requests = [];
    page.on('request', request => requests.push({ url: request.url(), method: request.method() }));
    async function download(sort = 'NIVEL', direction = 'desc') {
      const expected = (await (await fetch(`${base}/api/characters?pageSize=all&sort=${sort}&direction=${direction}`)).json()).characters;
      requests.length = 0;
      const event = page.waitForEvent('download');
      await button.click();
      const result = await event;
      assert.match(result.suggestedFilename(), /^nido-del-cuervo-personajes-\d{4}-\d{2}-\d{2}\.xlsx$/);
      const workbook = xlsx.read(fs.readFileSync(await result.path()), { type: 'buffer' });
      assert.deepEqual(Array.from(workbook.SheetNames), ['Personajes']);
      const rows = xlsx.utils.sheet_to_json(workbook.Sheets.Personajes, { header: 1, defval: null });
      assert.equal(rows.length, expected.length + 1);
      assert.deepEqual(Array.from(rows.slice(1), row => row[0]), expected.map(character => character.PERSONAJE));
      assert.equal(requests.length, 1);
      assert.equal(requests[0].method, 'GET');
      const params = new URL(requests[0].url).searchParams;
      assert.equal(params.get('pageSize'), 'all');
      assert.deepEqual([...params.keys()].sort(), ['direction', 'pageSize', 'sort']);
      return rows;
    }
    await download();
    assert.match(await page.locator('#page-status').innerText(), /Página 2/);
    await page.selectOption('#filter-class', { index: 1 });
    await settled();
    await page.fill('#name-search', 'NO-EXISTE-123');
    await page.waitForTimeout(350);
    await settled();
    assert.equal(await page.locator('#characters-body tr').count(), 0);
    assert.equal(await button.isEnabled(), true);
    await page.click('th[data-sort="CLASS"] button');
    await settled();
    await download('CLASS', 'asc');
    await page.evaluate(() => { window.originalWrite = XLSX.writeFile; XLSX.writeFile = () => { throw new Error('failure'); }; });
    await button.click();
    await page.waitForFunction(() => document.querySelector('#export-status').textContent.startsWith('No se pudo'));
    assert.equal(await button.isEnabled(), true);
    await page.evaluate(() => { XLSX.writeFile = window.originalWrite; });
    await page.route('**/api/characters?*', route => route.request().url().includes('pageSize=all') ? route.fulfill({ status: 503 }) : route.continue());
    await button.click();
    await page.waitForFunction(() => document.querySelector('#export-status').textContent.startsWith('No se pudo'));
    assert.equal(await button.isEnabled(), true);
    await page.unroute('**/api/characters?*');
    await download('CLASS', 'asc');
    await page.click('#reset-filters');
    await settled();
    await page.click('#edit-button');
    assert.equal(await button.isDisabled(), true);
    await page.click('#edit-button');
    assert.equal(await button.isEnabled(), true);
    let release;
    await page.route('**/api/characters?*', async route => {
      if (route.request().url().includes('pageSize=all')) await new Promise(resolve => { release = resolve; });
      await route.continue();
    });
    const pendingDownload = page.waitForEvent('download');
    await button.click();
    await page.waitForTimeout(100);
    assert.equal(await button.isDisabled(), true);
    assert.equal(await page.locator('#edit-button').isDisabled(), true);
    release();
    await pendingDownload;
    await page.unroute('**/api/characters?*');
    await button.focus();
    const keyboardDownload = page.waitForEvent('download');
    await page.keyboard.press('Enter');
    await keyboardDownload;
    for (const width of [1440, 390, 320]) {
      await page.setViewportSize({ width, height: 900 });
      const box = await button.boundingBox();
      assert(box.x >= 0 && box.x + box.width <= width);
    }
    assert.deepEqual(errors, []);
    console.log('Export and pagination verified: complete roster from page 2 and empty filtered view, order, GET only, errors/retry, editing lock, keyboard and mobile. No database writes.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
