const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
  const base = process.argv[2] || 'http://127.0.0.1:8788';
  assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname));
  const read = async () => (await (await fetch(base + '/api/characters?pageSize=all')).json()).characters;
  const initial = await read();
  const originals = new Map();
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1700, height: 1100 }, colorScheme: 'dark' });
  const errors = [], writes = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.method() === 'PATCH') writes.push(request.postDataJSON()); });
  const settled = () => page.waitForFunction(() => document.querySelector('.results').getAttribute('aria-busy') === 'false' && document.querySelector('#error-state').hidden);
  const row = id => page.locator(`tr[data-character-id="${id}"]`);
  const patch = async (id, fields) => {
    const current = (await read()).find(item => item.id === id);
    const response = await fetch(base + '/api/characters/batch', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ changes: [{ id, expectedVersion: current.version, fields }] }) });
    assert.equal(response.status, 200);
  };
  try {
    await page.goto(base); await settled();
    assert.equal(await page.locator('tbody tr').count(), 50);
    const firstId = await page.locator('tbody tr').first().getAttribute('data-character-id');
    originals.set(firstId, initial.find(item => item.id === firstId));
    await page.click('#edit-button');
    await row(firstId).locator('textarea').fill('Borrador primera página');
    await page.click('#next-page'); await settled();
    assert.equal(await page.locator('tbody tr').count(), 50);
    const secondId = await page.locator('tbody tr').first().getAttribute('data-character-id');
    originals.set(secondId, initial.find(item => item.id === secondId));
    await row(secondId).locator('textarea').fill('Borrador segunda página');
    await page.click('#previous-page'); await settled();
    assert.equal(await row(firstId).locator('textarea').inputValue(), 'Borrador primera página');
    await page.click('#edit-button'); await settled();
    assert.equal(writes.length, 1);
    assert.equal(writes[0].changes.length, 2);
    const saved = await read();
    assert.equal(saved.find(item => item.id === firstId).NOTAS, 'Borrador primera página');
    assert.equal(saved.find(item => item.id === secondId).NOTAS, 'Borrador segunda página');
    const last = initial.at(-1);
    await page.fill('#name-search', last.PERSONAJE.toLocaleUpperCase('es'));
    await page.waitForFunction(id => [...document.querySelectorAll('tbody tr')].some(row => row.dataset.characterId === id), last.id);
    assert.equal(await row(last.id).count(), 1);
    await page.click('#reset-filters'); await settled();
    await page.selectOption('#page-size', '20'); await settled();
    assert.equal(await page.locator('tbody tr').count(), 20);
    await page.selectOption('#page-size', '100'); await settled();
    assert.equal(await page.locator('tbody tr').count(), 100);
    await page.selectOption('#page-size', 'all'); await settled();
    assert.equal(await page.locator('tbody tr').count(), initial.length);
    await page.selectOption('#page-size', '20'); await settled();
    await page.click('#edit-button');
    await row(firstId).locator('textarea').fill('Propuesta fuera de página');
    await page.click('#next-page'); await settled();
    await patch(firstId, { NOTAS: 'Cambio concurrente' });
    await page.click('#edit-button');
    await page.waitForFunction(() => !document.querySelector('#refresh-draft').hidden);
    await page.click('#refresh-draft');
    await page.waitForFunction(() => document.querySelector('#refresh-draft').hidden);
    await page.click('#previous-page'); await settled();
    assert.equal(await row(firstId).locator('textarea').inputValue(), 'Propuesta fuera de página');
    await page.click('#edit-button'); await settled();
    assert.equal((await read()).find(item => item.id === firstId).NOTAS, 'Propuesta fuera de página');
    await page.click('#edit-button');
    await row(firstId).locator('input[data-editor="PERSONAJE"]').fill('Árbol_007%');
    await page.click('#edit-button'); await settled();
    await page.fill('#name-search', 'ÁRBOL_007%');
    await page.waitForFunction(id => document.querySelector('tbody tr')?.dataset.characterId === id && document.querySelector('tbody input') === null && document.querySelectorAll('tbody tr').length === 1, firstId);
    assert.equal(await page.locator('tbody tr').count(), 1);
    await page.click('#reset-filters'); await settled();
    await page.route('**/api/characters?**', async route => {
      if (new URL(route.request().url()).searchParams.get('search') === 'fallo') await route.fulfill({ status: 503, body: '{}' });
      else await route.continue();
    });
    await page.fill('#name-search', 'fallo'); await page.waitForSelector('#error-state:not([hidden])');
    await page.fill('#name-search', last.PERSONAJE);
    await page.waitForFunction(id => document.querySelector('tbody tr')?.dataset.characterId === id, last.id);
    await page.unroute('**/api/characters?**');
    await page.click('#reset-filters'); await settled();
    await page.selectOption('#page-size', '50'); await settled();
    await page.locator('.pagination').screenshot({ path: 'specs/007-paginacion/local-paginador.png' });
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
    await mobile.goto(base); await mobile.waitForSelector('tbody tr');
    assert.equal(await mobile.locator('tbody tr').count(), 20);
    assert.equal(await mobile.locator('#page-size').inputValue(), '20');
    assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await mobile.locator('.pagination').screenshot({ path: 'specs/007-paginacion/local-paginador-movil.png' });
    await mobile.setViewportSize({ width: 1400, height: 900 });
    assert.equal(await mobile.locator('#page-size').inputValue(), '20');
    await mobile.close();
    assert.deepEqual(errors, []);
    console.log('Chrome local: páginas, tamaños, borradores, lote único, conflicto fuera de página, nombre Unicode, error/reintento y móvil pasan.');
  } finally {
    await browser.close();
    for (const [id, original] of originals) await patch(id, { PERSONAJE: original.PERSONAJE, NOTAS: original.NOTAS });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
