import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import fs from 'node:fs/promises';
import path from 'node:path';
import { onRequest as patchHandler } from '../functions/api/characters/batch.js';
import { createCharacterWorkbook } from '../export-excel.js';
const require = createRequire(import.meta.url);
const { Miniflare, convertV4MiniflareOptions } = require(process.env.MINIFLARE_MODULE || 'miniflare');
const XLSX = require('../vendor/xlsx.full.min.js');
const base = process.argv[2] ?? 'http://127.0.0.1:8788';
assert.ok(['localhost', '127.0.0.1'].includes(new URL(base).hostname));
const config = JSON.parse(await fs.readFile('wrangler.jsonc', 'utf8'));
assert.equal(config.d1_databases[0].remote, false);
const runtime = new Miniflare(convertV4MiniflareOptions({ modules: true, script: 'export default {}', resourcePersistencePath: path.resolve('.wrangler/state/v3'), d1Databases: { DB: config.d1_databases[0].database_id } }));
const db = await runtime.getD1Database('DB');
const read = async (query = 'pageSize=all') => { const response = await fetch(`${base}/api/characters?${query}`); assert.equal(response.status, 200, await response.clone().text()); return response.json(); };
const patch = async (changes, catalogAdditions) => fetch(`${base}/api/characters/batch`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ changes, ...(catalogAdditions ? { catalogAdditions } : {}) }) });
const post = async body => fetch(`${base}/api/characters`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
const change = (character, fields) => ({ id: character.id, expectedVersion: character.version, fields });
const initial = await read();
const originals = (await db.prepare('SELECT * FROM characters ORDER BY sourceRow').all()).results;
const prefix = `Borrado ${randomUUID().slice(0, 8)}`;
const operations = [];
async function fixture(name = prefix) {
  const body = { id: randomUUID(), fields: { PERSONAJE: name, CLASS: initial.catalogs.classes[0].name, SPECIE: initial.catalogs.species[0].name, PROPIETARIO: prefix, NIVEL: 20, NOTAS: 'Datos conservados' } };
  operations.push(body);
  const response = await post(body); assert.equal(response.status, 201, await response.clone().text());
  return (await response.json()).character;
}
const stored = async id => (await read(`ids=${id}`)).characters[0];
try {
  assert.ok(initial.characters.every(item => item.is_deleted === false));
  assert.ok(originals.every(item => item.is_deleted === 0));
  const a = await fixture(), b = await fixture();
  for (const value of [false, null, 0, 1, 'true']) assert.equal((await patch([change(a, { is_deleted: value })])).status, 422);
  assert.equal((await post({ ...operations[0], fields: { ...operations[0].fields, is_deleted: true } })).status, 400);
  assert.equal((await patch([change(a, { PERSONAJE: `${prefix} guardado`, NIVEL: 3, is_deleted: true }), change(b, { NOTAS: 'Edición en lote mixto' })])).status, 200);
  const deleted = await stored(a.id);
  assert.equal(deleted.is_deleted, true); assert.equal(deleted.PERSONAJE, `${prefix} guardado`); assert.equal(deleted.NIVEL, 3); assert.equal(deleted.RANGO, 'Cuervo blanco'); assert.equal(deleted.version, 1);
  for (const key of ['id', 'CLASS', 'SUBCLASS', 'SPECIE', 'ESTADO', 'PROPIETARIO', 'NOTAS', 'sourceRow']) assert.equal(deleted[key], a[key]);
  assert.equal((await db.prepare('SELECT name_search FROM characters WHERE id = ?').bind(a.id).first()).name_search, `${prefix} guardado`.toLowerCase());
  assert.equal((await stored(b.id)).is_deleted, false);
  assert.equal((await patch([change(deleted, { is_deleted: true })])).status, 409);
  assert.equal((await patch([change(deleted, { NOTAS: 'No escribir' }), change(await stored(b.id), { NOTAS: 'Tampoco escribir' })])).status, 409);
  assert.equal((await stored(b.id)).NOTAS, 'Edición en lote mixto');
  const repeated = await post(operations[0]); assert.equal(repeated.status, 200); assert.equal((await repeated.json()).character.is_deleted, true);
  const all = await read(); assert.ok(all.pagination.totalRecords > 203); assert.ok(!all.characters.some(item => item.id === a.id));
  for (const sort of ['CLASS', 'SUBCLASS', 'SPECIE', 'RANGO', 'PROPIETARIO']) assert.ok(!(await read(`pageSize=all&sort=${sort}`)).characters.some(item => item.id === a.id));
  assert.equal((await read(`search=${encodeURIComponent(deleted.PERSONAJE)}`)).pagination.totalMatches, 0);
  const missing = randomUUID(); const byIds = await read(`ids=${a.id},${b.id},${missing}`); assert.deepEqual(byIds.missingIds, [missing]); assert.equal(byIds.characters.find(item => item.id === a.id).is_deleted, true);
  const workbook = createCharacterWorkbook(all.characters, XLSX); const rows = XLSX.utils.sheet_to_json(workbook.Sheets.Personajes);
  assert.equal(rows.length, all.pagination.totalRecords); assert.ok(!rows.some(row => row.Personaje === deleted.PERSONAJE)); assert.equal(XLSX.utils.sheet_to_json(workbook.Sheets.Personajes, { header: 1 })[0].length, 9);
  const race = await fixture(); const contenders = await Promise.all([patch([change(race, { is_deleted: true })]), patch([change(race, { PERSONAJE: `${prefix} carrera` })])]);
  assert.deepEqual(contenders.map(item => item.status).sort(), [200, 409]); assert.equal((await stored(race.id)).version, 1);
  const twice = await fixture(); assert.deepEqual((await Promise.all([patch([change(twice, { is_deleted: true })]), patch([change(twice, { is_deleted: true })])])).map(item => item.status).sort(), [200, 409]);
  const newClass = `${prefix} clase`, newSub = `${prefix} sub`;
  const catalogRow = await fixture();
  assert.equal((await patch([change(catalogRow, { CLASS: newClass, SUBCLASS: newSub, is_deleted: true })], { classes: [newClass], subclasses: [{ className: newClass, name: newSub }] })).status, 200);
  assert.equal((await stored(catalogRow.id)).SUBCLASS, newSub);
  assert.ok((await read()).catalogs.classes.some(item => item.name === newClass));
  const rollback = await fixture(); const rollbackSpecies = `${prefix} rollback`;
  await db.prepare(`CREATE TRIGGER test_soft_delete_rollback BEFORE UPDATE ON characters WHEN NEW.id = '${rollback.id}' BEGIN SELECT RAISE(ABORT, 'forced'); END`).run();
  assert.equal((await patch([change(rollback, { SPECIE: rollbackSpecies, is_deleted: true })], { species: [rollbackSpecies] })).status, 503);
  assert.deepEqual(await stored(rollback.id), rollback); assert.ok(!(await read()).catalogs.species.some(item => item.name === rollbackSpecies));
  await db.prepare('DROP TRIGGER test_soft_delete_rollback').run();
  const guarded = await fixture(); const guardedSpecies = `${prefix} guardia`;
  let guardPending = false;
  const wrapped = { prepare: sql => { if (sql.includes('UPDATE characters')) guardPending = true; return db.prepare(sql); }, batch: async statements => {
    if (guardPending) await db.prepare('UPDATE characters SET is_deleted = 1, version = version + 1 WHERE id = ?').bind(guarded.id).run();
    return db.batch(statements);
  } };
  const intercepted = await patchHandler({ request: new Request(`${base}/api/characters/batch`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ changes: [change(guarded, { SPECIE: guardedSpecies, is_deleted: true })], catalogAdditions: { species: [guardedSpecies] } }) }), env: { DB: wrapped } });
  assert.equal(intercepted.status, 409); assert.ok(!(await read()).catalogs.species.some(item => item.name === guardedSpecies));
  const pageBefore = await read('page=999&pageSize=20');
  const last = pageBefore.characters.at(-1); await db.prepare('UPDATE characters SET is_deleted = 1 WHERE id = ?').bind(last.id).run();
  const pageAfter = await read('page=999&pageSize=20'); assert.ok(pageAfter.pagination.page <= pageBefore.pagination.page); assert.equal(pageAfter.pagination.totalRecords, pageBefore.pagination.totalRecords - 1);
  await db.prepare('UPDATE characters SET is_deleted = 1').run();
  const empty = await read(); assert.equal(empty.pagination.totalRecords, 0); assert.equal(empty.characters.length, 0); assert.equal(empty.editOptions.PROPIETARIO.length, 0); assert.equal(empty.filterOptions.CLASS.length, 0); assert.ok(empty.catalogs.species.length > 0);
  console.log('Soft delete API: data preservation, edited deletion, mixed batch, validation, replay, races, guards, rollback, active queries/Excel, zero-active and pagination pass.');
} finally {
  await db.prepare('DROP TRIGGER IF EXISTS test_soft_delete_rollback').run();
  for (const operation of operations) { await db.prepare('DELETE FROM creation_requests WHERE character_id = ?').bind(operation.id).run(); await db.prepare('DELETE FROM characters WHERE id = ?').bind(operation.id).run(); }
  for (const character of originals) await db.prepare('UPDATE characters SET is_deleted = ? WHERE id = ?').bind(character.is_deleted, character.id).run();
  await db.prepare('DELETE FROM subclasses WHERE name LIKE ?').bind(`${prefix}%`).run();
  await db.prepare('DELETE FROM classes WHERE name LIKE ?').bind(`${prefix}%`).run();
  await db.prepare('DELETE FROM species WHERE name LIKE ?').bind(`${prefix}%`).run();
  assert.deepEqual(await read(), initial);
  await runtime.dispose();
}
