const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
(async () => {
const base=process.argv[2] || 'http://127.0.0.1:8788';
assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname), 'Solo pruebas locales.');
const initial=(await (await fetch(base+'/api/characters')).json()).characters;
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'dark'});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
let writes=0; page.on('request',r=>{if(r.method()==='PATCH') writes++;});
const button=(id,delta)=>page.locator(`button[data-character-id="${id}"][data-delta="${delta}"]`);
try {
await page.goto(base); await page.waitForSelector('tbody tr');
assert.equal(await page.locator('tbody tr').count(),203);
await page.click('#edit-button');
const id=await page.locator('button[data-character-id]').first().getAttribute('data-character-id');
const orig=initial.find(x=>x.id===id);
for(let i=0;i<5;i++) await button(id,1).click();
assert.equal(await page.locator('#draft-status').textContent(),'1 personajes modificados');
assert.equal(await button(id,1).isDisabled(),true);
assert.equal(writes,0);
for(let i=0;i<5;i++) await button(id,-1).click();
assert.equal(await page.locator('#draft-status').textContent(),'0 personajes modificados');
await button(id,1).click();
const id2=initial.find(x=>x.id!==id).id;
await button(id2,1).click();
await page.screenshot({path:'.local/local-edicion.png'});
await page.click('#edit-button'); await page.waitForFunction(()=>document.querySelector('#edit-button').textContent==='Editar');
assert.equal(writes,1);
await page.reload(); await page.waitForSelector('tbody tr');
const current=(await (await fetch(base+'/api/characters')).json()).characters.find(x=>x.id===id);
assert.equal(current.NIVEL,orig.NIVEL+1);
await page.click('#edit-button'); await button(id,1).click();
await fetch(base+'/api/characters/batch',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({changes:[{id,expectedVersion:current.version,fields:{NIVEL:current.NIVEL-1}}]})});
await page.click('#edit-button'); await page.waitForSelector('#refresh-draft:visible');
assert.equal(await page.locator('tr.pending').count(),1);
await page.click('#refresh-draft'); await page.waitForFunction(()=>!document.querySelector('#edit-button').disabled);
assert.match(await page.locator('#draft-status').textContent(),/tu propuesta/);
await page.click('#edit-button'); await page.waitForFunction(()=>document.querySelector('#edit-button').textContent==='Editar');
await page.click('#edit-button'); await button(id,-1).click();
await page.route('**/api/characters/batch',async route=>{await route.fetch(); await route.abort('failed');});
await page.click('#edit-button'); await page.waitForSelector('#refresh-draft:visible');
await page.unroute('**/api/characters/batch');
await page.click('#refresh-draft'); await page.waitForFunction(()=>!document.querySelector('#edit-button').disabled);
assert.equal(await page.locator('tr.pending').count(),0);
const beforeEmpty=writes; await page.click('#edit-button'); assert.equal(writes,beforeEmpty);
await page.locator('#name-search').fill(orig.PERSONAJE.slice(0,3));
assert.ok(await page.locator('tbody tr').count()>=1); assert.ok(await page.locator('tbody tr').count()<203);
await page.click('#reset-filters'); assert.equal(await page.locator('tbody tr').count(),203);
await page.click('#theme-toggle');
assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
await page.setViewportSize({width:390,height:844}); await page.click('#edit-button');
await page.locator('.table-scroll').evaluate(el=>el.scrollLeft=el.querySelector('th:nth-child(5)').offsetLeft-100);
await page.screenshot({path:'.local/local-movil.png'});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await button(id,1).focus(); assert.equal(await button(id,1).evaluate(el=>el===document.activeElement),true);
assert.deepEqual(errors,[]);
console.log(JSON.stringify({rows:203,writes,conflictRecovery:true,uncertainNetworkRecovery:true,mobile:true,errors}));
} finally {
const latest=(await (await fetch(base+'/api/characters')).json()).characters;
const changes=latest.filter(c=>c.NIVEL!==initial.find(x=>x.id===c.id).NIVEL).map(c=>({id:c.id,expectedVersion:c.version,fields:{NIVEL:initial.find(x=>x.id===c.id).NIVEL}}));
if(changes.length) assert.equal((await fetch(base+'/api/characters/batch',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({changes})})).status,200);
await browser.close();
}
})();
