CREATE TABLE characters (
  id TEXT PRIMARY KEY NOT NULL,
  PERSONAJE TEXT,
  CLASS TEXT,
  SUBCLASS TEXT,
  SPECIE TEXT,
  NIVEL INTEGER NOT NULL CHECK(typeof(NIVEL) = 'integer' AND NIVEL BETWEEN 1 AND 20),
  RANGO TEXT NOT NULL,
  ESTADO TEXT,
  PROPIETARIO TEXT,
  NOTAS TEXT,
  sourceRow INTEGER NOT NULL UNIQUE,
  version INTEGER NOT NULL DEFAULT 0 CHECK(version >= 0)
);
